# Generated by Django 5.2.5 on 2025-09-10 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_bio'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileskill',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AddField(
            model_name='profileskill',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileskill',
            name='available_for_teaching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='learning_status',
            field=models.CharField(choices=[('learning', 'Learning'), ('practicing', 'Practicing'), ('mastered', 'Mastered'), ('teaching', 'Teaching')], default='learning', max_length=20),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='times_taught',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='token_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_icon',
            field=models.ImageField(blank=True, null=True, upload_to='skill_icons/'),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='personal_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
