# Generated by Django 5.2.5 on 2025-10-19 18:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_profileskill_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_icon',
            field=cloudinary.models.CloudinaryField(default='default.png', max_length=255, verbose_name='image'),
        ),
    ]
