# Generated by Django 5.2.5 on 2025-11-02 21:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_icon',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dctwxqpeo/image/upload/v1762118822/Skills-To-Learn_v7lkgs.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
