# Generated by Django 5.2.5 on 2025-08-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tokens_released',
            field=models.BooleanField(default=False),
        ),
    ]
