# Generated by Django 5.2.5 on 2025-09-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0002_booking_tokens_released'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tokens_released',
            new_name='tokens_completed_given',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='proposed_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='tokens_scheduled_given',
            field=models.BooleanField(default=False),
        ),
    ]
