# Generated by Django 5.2.5 on 2025-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0003_rename_tokens_released_booking_tokens_completed_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tokens_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
