# Generated by Django 5.2.5 on 2025-09-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0004_booking_meeting_link_booking_proposed_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='host_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
