# Generated by Django 5.2.5 on 2025-09-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0005_booking_host_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_started',
            field=models.BooleanField(default=False),
        ),
    ]
