# Generated by Django 5.2.5 on 2025-09-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mettings', '0006_booking_meeting_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
