# Generated by Django 5.2.5 on 2025-09-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_joined_on_profile_rating_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
