# Generated by Django 5.2.5 on 2025-11-02 21:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dctwxqpeo/image/upload/v1757868228/default_ehmhxs.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
