# Generated by Django 5.2.5 on 2026-01-28 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
