# Generated by Django 6.0.1 on 2026-01-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
